.TH "chrome-gnome-shell" "1" "8" "Raúl Romero García aka bgta" "openSUSE Build Service home project"
.SH "NAME"
\fBchrome-gnome-shell\fR is a Web extension for Google Chrome/Chromium, Vivaldi, Opera (and other WebExtensions capable browsers) and native host messaging connector that provides integration with GNOME Shell and the corresponding extensions repository https://extensions.gnome.org.
.br
.SH "SEE ALSO"
\fIhttps://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome\fR
.br
